version: '3'
services: 
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports: 
      - "8088:80"
    volumes:
      - ./application:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - app
      - mysql
    networks: 
      - laravel
    
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "4306:3306"
    volumes: 
      -  dbdata:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: flightadvisor
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: [--max-allowed-packet=671088640]
    networks: 
      - laravel

  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    volumes: 
      - ./application:/var/www
    networks: 
      - laravel

#Docker Networks
networks: 
  laravel:
    driver: bridge
volumes:
  dbdata:
    driver: local